### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by BrawlyTheInventor**
Added a GUI that SHOULD work on windows (I use Debian so...)

### CODE REVIEW

**Comment by TheBossProSniper** [comment]
Hey, fun fact, we're already working on a Gui for electric : ) , though thank you for this contribution, its helpful : )

**Comment by TheBossProSniper** [comment]
Update: It works well on windows, thanks for your effort, this works well as a temporary solution : P . We're working on the electric GUI using PyQt5 so lemme know how i can contact you so i can keep you updated on what we can do next!

**Comment by BrawlyTheInventor** [comment]
Yes, I have Discord

**Comment by TheBossProSniper** [comment]
Fantastic, feel free to send me a friend request or DM me with ```TheBossProSniper#7552```

**Pull request merged**
